### ISSUE TITLE
Refactor: stack(create|delete|status)

### ISSUE THREAD

**Issue by jaymccon** [taskcat/taskcat-v9#3]
https://github.com/taskcat/taskcat-v9/blob/master/taskcat/stacker.py#L677-L765
https://github.com/taskcat/taskcat-v9/blob/master/taskcat/stacker.py#L822-L858
https://github.com/taskcat/taskcat-v9/blob/master/taskcat/stacker.py#L1083-L1096

**Comment by andrew-glenn** [comment]
Stacker: Ensure all CF references use correct credentials
- See https://github.com/aws-quickstart/taskcat/issues/221

**Comment by avattathil** [comment]
@andrew-glenn @jaymccon I will take stack_launch.  Seems like a good place to jump on :-)

**Comment by jaymccon** [comment]
This is largely done already in the stack object https://github.com/taskcat/taskcat-v9/blob/master/taskcat/_cfn/stack.py all that's left is to wire it up to the test entrypoint

**Comment by avattathil** [comment]
> This is largely done already in the stack object https://github.com/taskcat/taskcat-v9/blob/master/taskcat/_cfn/stack.py all that's left is to wire it up to the test entrypoint

Cool will take a stab at the wiring. It will get be familiar with the v9 config object

**Comment by jaymccon** [comment]
done for real now 😺
