### ISSUE TITLE
special path `functions` should be named `lambda_functions`

### ISSUE THREAD

**Issue by jaymccon** [taskcat/taskcat-v9#8]
the path `functions` is currently special purpose, `functions/source` subfolder is excluded from s3 upload, and `package_lambda: true` in config will package source folders into lambda zips in `functions/packages`.

Name should be `lambda_functions` to be more explicit and avoid confusion.

**Comment by avattathil** [comment]
I would say when verbose logging is on also add a msg that states `[INFO]:` Skipping upload of source file.

**Comment by avattathil** [comment]
Also what is everyones thoughts on generating the package by default  if `lambda_functions/source
` is found unless `package_lambda: false` explicitly

**Comment by andrew-glenn** [comment]
✅ Enhancements tag, as the Lambda PR has already been merged. If we decide to do this, it'll need adjustments here.

https://github.com/taskcat/taskcat-v9/blob/3baf712864abc74a3cdc5836ce7b932deaf77ae0/taskcat/_config.py#L84-L88

**Comment by jaymccon** [comment]
resolved in #54
